# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prerequisits on the host:
# - brew install bash bison coreutils ninja cmake
# - sudo arrow/ci/scripts/install_python.sh macos 3.9


# NOTE: must set "Crossbow" as name to have the badge links working in the
# github comment reports!
name: Crossbow
on:
  push:
    branches:
      - "*-github-*"


env:
  ARROW_FLIGHT: OFF
  ARROW_JEMALLOC: OFF
  ARROW_SIMD_LEVEL: "NONE"
  CC: "clang"
  CMAKE_BUILD_TYPE: release
  CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
  CXX: "clang++"
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  PYARROW_BUILD_VERBOSE: 1
  PYARROW_VERSION: "8.0.0.dev493"
  PYTHON_VERSION: "3.9"
  PYTHON: "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9"
  VCPKG_DEFAULT_TRIPLET: universal2-osx-static-release
  VCPKG_FEATURE_FLAGS: "manifests"
  VCPKG_OVERLAY_TRIPLETS: ${{ github.workspace }}/arrow/ci/vcpkg
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    name: Build wheel for OS X
    runs-on: self-hosted
    steps:
      - name: Cleanup
        shell: bash
        run: rm -rf arrow vcpkg build crossbow-env build-env test-*-env

      - name: Checkout Arrow
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: arrow
          repository: apache/arrow
          ref: 24b48083f102ef9366adb0797f5f8fa53c188a7b
          submodules: recursive


      - name: Add Brew's Bison to PATH
        shell: bash
        run: echo "/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH

      - name: Retrieve VCPKG version from arrow/.env
        shell: bash
        run: |
          vcpkg_version=$(cat "arrow/.env" | grep "VCPKG" | cut -d "=" -f2 | tr -d '"')
          echo "VCPKG_VERSION=$vcpkg_version" >> $GITHUB_ENV

      - name: Install Vcpkg
        shell: bash
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: arch -arm64 arrow/ci/scripts/install_vcpkg.sh $VCPKG_ROOT $VCPKG_VERSION

      - name: Add Vcpkg to PATH
        shell: bash
        run: echo ${VCPKG_ROOT} >> $GITHUB_PATH

      - name: Install OpenSSL
        shell: bash
        run: arch -arm64 vcpkg install openssl:arm64-osx-static-release

      - name: Install Packages
        run: |
           arch -arm64 vcpkg install \
            --clean-after-build \
            --x-install-root=${VCPKG_ROOT}/installed \
            --x-manifest-root=arrow/ci/vcpkg \
            --x-feature=flight \
            --x-feature=gcs \
            --x-feature=json \
            --x-feature=parquet

      # OpenSSL doesn't provide an universal2 configuration yet, so vcpkg is
      # unable to propagate the list of architectures from VCPKG_OSX_ARCHIETCTURES.
      # In order to prevent link time warnings (which may turn out to be errors)
      # we compile OpenSSL separately for the two architectures and merge the
      # binaries into universal2 ones using `lipo`.
      - name: Create universal binaries for OpenSSL
        shell: bash
        run: |
          mkdir -p $VCPKG_ROOT/installed/universal2-osx-static-release/lib
          for arch in arm64 amd64; do
            arch -arm64 vcpkg install openssl:${arch}-osx-static-release
          done
          for lib in libcrypto libssl; do
            lipo -create $VCPKG_ROOT/installed/arm64-osx-static-release/lib/${lib}.a \
                         $VCPKG_ROOT/installed/amd64-osx-static-release/lib/${lib}.a \
                 -output $VCPKG_ROOT/installed/universal2-osx-static-release/lib/${lib}.a
          done

      - name: Build Wheel
        shell: bash
        run: |
          $PYTHON -m venv build-env
          source build-env/bin/activate
          pip install --upgrade pip wheel
          arch -arm64 arrow/ci/scripts/python_wheel_macos_build.sh universal2 $(pwd)/arrow $(pwd)/build

      - name: Test Wheel on ARM64
        shell: bash
        env:
          PYTEST_ADDOPTS: "-k 'not test_cancellation'"
        run: |
          $PYTHON -m venv test-arm64-env
          source test-arm64-env/bin/activate
          pip install --upgrade pip wheel
          arch -arm64 arrow/ci/scripts/python_wheel_unix_test.sh $(pwd)/arrow

      - name: Test Wheel on AMD64
        shell: bash
        env:
          PYTEST_ADDOPTS: "-k 'not test_cancellation'"
        run: |
          $PYTHON -m venv test-amd64-env
          source test-amd64-env/bin/activate
          pip install --upgrade pip wheel
          arch -x86_64 arrow/ci/scripts/python_wheel_unix_test.sh $(pwd)/arrow

      - name: Upload artifacts
        shell: bash
        run: |
          $PYTHON -m venv crossbow-env
          source crossbow-env/bin/activate
          arch -x86_64 pip install -e arrow/dev/archery[crossbow-upload]
          arch -x86_64 archery crossbow \
          --queue-path $(pwd) \
          --queue-remote https://github.com/ursacomputing/crossbow \
          upload-artifacts \
          --sha nightly-packaging-2022-04-22-0-github-wheel-macos-big-sur-cp39-universal2 \
          --tag nightly-packaging-2022-04-22-0-github-wheel-macos-big-sur-cp39-universal2 \
          "arrow/python/repaired_wheels/*.whl"
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Upload package to Gemfury
        shell: bash
        run: |
          path=$(ls arrow/python/repaired_wheels/*.whl)
          curl -F "package=@${path}" https://${CROSSBOW_GEMFURY_TOKEN}@push.fury.io/${CROSSBOW_GEMFURY_ORG}/
        env:
          CROSSBOW_GEMFURY_TOKEN: ${{ secrets.CROSSBOW_GEMFURY_TOKEN }}
          CROSSBOW_GEMFURY_ORG: ${{ secrets.CROSSBOW_GEMFURY_ORG }}
